### ISSUE TITLE
Mainnet account creation fail

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1052]
### Problem description
Can not setup Standard Registry with mainnet account

### Step to reproduce
1. config guardian using mainnet 
2. initialise Standard Registry
3. Got below error

### Expected behavior
We need guideline how to setup the INITIALIZATION_TOPIC_ID on mainnet  or we need a pre-defined INITIALIZATION_TOPIC_ID that available on mainnet .

### Screenshots
error logs captured

```

Error: guardians (CREATE_USER_PROFILE) send: receipt for transaction 0.0.xxxxxxxx@1656573300.837624375 contained error status INVALID_TOPIC_ID
    at Guardians.<anonymous> (/usr/api-gateway/dist/helpers/serviceRequestsBase.js:49:29)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/api-gateway/dist/helpers/serviceRequestsBase.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

```
StatusError: receipt for transaction 0.0.xxxxxxx@1656573300.837624375 contained error status INVALID_TOPIC_ID
    at new ReceiptStatusError (/usr/guardian-service/node_modules/@hashgraph/sdk/lib/ReceiptStatusError.cjs:45:5)
    at TransactionReceiptQuery._mapStatusError (/usr/guardian-service/node_modules/@hashgraph/sdk/lib/transaction/TransactionReceiptQuery.cjs:301:12)
    at TransactionReceiptQuery.execute (/usr/guardian-service/node_modules/@hashgraph/sdk/lib/Executable.cjs:670:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionResponse.getReceipt (/usr/guardian-service/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:100:21)
    at async TransactionResponse.getRecord (/usr/guardian-service/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:119:5)

```

**Comment by anvabr** [comment]
This is of course because the mainnet INIT topic (for the ‘hello world’ messages) does not exist. While the INIT topic is ‘free to post’ for anyone, I feel this topic probably needs to be created on the mainnet from an account controlled by Hedera (i.e. ‘official’ account of some sort). @dubgeis or @sergmetelin for comment?

**Comment by samuraitruong** [comment]
@anvabr Thanks, yes create the topic on mainnet will solve problem?

is that hello world topic need to create by every account using guardian to keep them separate?

**Comment by voycey** [comment]
Hey @anvabr - I will be posting this in our Guardian chat for inclusion on the next call but we have spoken with Wes and we are pushing ahead with what was discussed on the tech call - we have created the well known file `0.0.1032078` which contains a link to the 2 ESG topics for discovery:

```
0.0.1032076     ESG Hello World 1       Carbon / ESG
0.0.1032077     ESG Hello World 2       Carbon / ESG
```
