### ISSUE TITLE
Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1370]
### Problem description
```js

DriverException: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in. at MongoExceptionConverter.convertException (/usr/guardian-service/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16) at MongoExceptionConverter.convertException (/usr/guardian-service/node_modules/@mikro-orm/mongodb/MongoExceptionConverter.js:17:22) at MongoDriver.convertException (/usr/guardian-service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:192:54) at /usr/guardian-service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:196:24 at processTicksAndRejections (node:internal/process/task_queues:96:5) at async MongoDriver.find (/usr/guardian-service/node_modules/@mikro-orm/mongodb/MongoDriver.js:24:21) at async MongoEntityManager.find (/usr/guardian-service/node_modules/@mikro-orm/core/EntityManager.js:106:25)

```

I think that happen when Aggregate logs attributes, In our database we have about 1.5M logs. we produce about 1M log weekly so this will grow very fast.

When this happen, guardian service will crashed

Note: this also related to missing index on log table

### Expected behavior
- Better log attributes aggregate
- Guardian service should not crashed when any even handler error.

**Comment by anvabr** [comment]
Proposed solution: change the code to add below option when call `aggregate()` function

`allowDiskUse: true `
