### ISSUE TITLE
Guardian-service crashing when mongo collection growth

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1435]
### Problem description
We start to get lots of below error 

```
Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.
    at Connection.onMessage (/usr/guardian-service/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/usr/guardian-service/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (/usr/guardian-service/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/usr/guardian-service/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22) NR
```

This similar with aggregate() function report before but this time it apply to find command. I raise it as separate issue for us to look at the option that can avoid this issue for all other command

At the moment we have about
VC = 250k ~ 1GB
VP =  7k ~700MB

Please note that when this issue happen , guardian -service will crash and restart as we have self recover but it will create the performance and maybe lost some realtime processing request.

**Comment by anvabr** [comment]
@samuraitruong thank you for the report, we have done investigation and analysis internally and determined that the most appropriate resolution for this is to ensure version compatibility of mongodb by restricting the version to (only) mongo 6. We have [fixed docker-compose.yml in 'dev'](https://github.com/hashgraph/guardian/commit/8a251cedf86022f5b89ab562b19b3f3585632fdd), and will update the doc accordingly.
