### ISSUE TITLE
sendToGuardianBlock throw exception

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#2133]
### Problem description
```

2023-05-12 15:59:33 /usr/local/policy-service/node_modules/@mikro-orm/core/entity/EntityAssigner.js:45
2023-05-12 15:59:33             throw new Error(`You must pass a non-${value} value to the property ${propName} of entity ${entity.constructor.name}.`);
2023-05-12 15:59:33                   ^
2023-05-12 15:59:33 
2023-05-12 15:59:33 Error: You must pass a non-undefined value to the property createDate of entity BlockState.
2023-05-12 15:59:33     at Function.assignProperty (/usr/local/policy-service/node_modules/@mikro-orm/core/entity/EntityAssigner.js:45:19)
2023-05-12 15:59:33     at /usr/local/policy-service/node_modules/@mikro-orm/core/entity/EntityAssigner.js:30:35
2023-05-12 15:59:33     at Array.forEach (<anonymous>)
2023-05-12 15:59:33     at Function.assign (/usr/local/policy-service/node_modules/@mikro-orm/core/entity/EntityAssigner.js:29:27)
2023-05-12 15:59:33     at WrappedEntity.assign (/usr/local/policy-service/node_modules/@mikro-orm/core/entity/WrappedEntity.js:54:48)
2023-05-12 15:59:33     at DataBaseHelper.<anonymous> (/usr/local/policy-service/node_modules/@guardian/common/dist/helpers/db-helper.js:347:50)
2023-05-12 15:59:33     at Generator.next (<anonymous>)
2023-05-12 15:59:33     at fulfilled (/usr/local/policy-service/node_modules/@guardian/common/dist/helpers/db-helper.js:40:26)
2023-05-12 15:59:33     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This error happen with latest version 2.12.1 . not sure how the BlockState get messed up but we can not add new VC via UI/API any more

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the ticket. We are unable to reproduce this issue internally.
Can you please help us out in providing more info such as policy timestamp, data being used.
Thanks,
Prernaa

**Comment by samuraitruong** [comment]
@prernaadev01  this issue was gone after I restart the policy-service & guardian-service. when I saw this again I will try to the right policy timestamp. Nothing is wrong with the policy because I use that policy for awhile. I wonder if any cache issue by Mikro ORM. or maybe we need to sure that createdDate is always set to current if it is empty/null/undefined
