### ISSUE TITLE
policy-service port in use issue

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#2144]
### Problem description
when there are many policies in guardian (we have 40 policies) below error happy very often in policy service

```


ode:events:491
2023-05-17 14:25:15       throw er; // Unhandled 'error' event
2023-05-17 14:25:15       ^
2023-05-17 14:25:15 
2023-05-17 14:25:15 Error: listen EADDRINUSE: address already in use :::52184
2023-05-17 14:25:15     at Server.setupListenHandle [as _listen2] (node:net:1463:16)
2023-05-17 14:25:15     at listenInCluster (node:net:1511:12)
2023-05-17 14:25:15     at Server.listen (node:net:1599:7)
2023-05-17 14:25:15     at Function.listen (/usr/local/policy-service/node_modules/express/lib/application.js:635:24)
2023-05-17 14:25:15     at LargePayloadContainer.runServer (/usr/local/policy-service/node_modules/@guardian/common/dist/mq/large-payload-container.js:59:13)
2023-05-17 14:25:15     at /usr/local/policy-service/dist/api/policy-process.js:91:46
2023-05-17 14:25:15     at Generator.next (<anonymous>)
2023-05-17 14:25:15     at fulfilled (/usr/local/policy-service/dist/api/policy-process.js:5:58)
2023-05-17 14:25:15     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-05-17 14:25:15 Emitted 'error' event on Server instance at:
2023-05-17 14:25:15     at emitErrorNT (node:net:1490:8)
2023-05-17 14:25:15     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2023-05-17 14:25:15   code: 'EADDRINUSE',
2023-05-17 14:25:15   errno: -98,
2023-05-17 14:25:15   syscall: 'listen',
2023-05-17 14:25:15   address: '::',
2023-05-17 14:25:15   port: 52184
2023-05-17 14:25:15 }
```

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the ticket.
We would suggest you to add ports for each Service in respective .env files and try it once.
Please let us know if it works.
Thanks,
Prernaa
