### ISSUE TITLE
guardian-service start with error: PrecheckStatusError: transaction ... failed precheck with status TRANSACTION_EXPIRED

### ISSUE THREAD

**Issue by engineforce** [hashgraph/guardian#31]
**Describe the bug**
guardian-service start with error: `PrecheckStatusError: transaction ... failed precheck with status TRANSACTION_EXPIRED`

**To Reproduce**
1. Clone main (cbbfd3bcde9c25500cba31845aaa3b94dccda7b9) 
2. Update OPERATOR_ID and OPERATOR_KEY in .env, .env.docker and config.json
3. `docker-compose up -d --build`
4. `docker-compose logs -f guardian-service`
5. See following error
```
guardian-service_1  |
guardian-service_1  | > guardian-service@1.0.0-beta.2 start
guardian-service_1  | > node dist/index.js
guardian-service_1  |
guardian-service_1  | /usr/vc-modules/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23
guardian-service_1  |     super(props, `transaction ${props.transactionId.toString()} failed precheck with status ${props.status.toString()}`);
guardian-service_1  |     ^
guardian-service_1  |
guardian-service_1  | PrecheckStatusError: transaction 0.0.3013031@1636335862.927085674 failed precheck with status TRANSACTION_EXPIRED
guardian-service_1  |     at new PrecheckStatusError (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)
guardian-service_1  |     at TopicCreateTransaction._mapStatusError (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:944:12)
guardian-service_1  |     at TopicCreateTransaction.execute (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/Executable.cjs:391:22)
guardian-service_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
guardian-service_1  |   status: Status { _code: 4 },
guardian-service_1  |   transactionId: TransactionId {
guardian-service_1  |     accountId: AccountId {
guardian-service_1  |       shard: Long { low: 0, high: 0, unsigned: false },
guardian-service_1  |       realm: Long { low: 0, high: 0, unsigned: false },
guardian-service_1  |       num: Long { low: 3013031, high: 0, unsigned: false },
guardian-service_1  |       _checksum: null
guardian-service_1  |     },
guardian-service_1  |     validStart: Timestamp {
guardian-service_1  |       seconds: Long { low: 1636335862, high: 0, unsigned: false },
guardian-service_1  |       nanos: Long { low: 927085674, high: 0, unsigned: false }
guardian-service_1  |     },
guardian-service_1  |     scheduled: false
guardian-service_1  |   }
guardian-service_1  | }
```

**Expected behavior**
guardian-service should start without error.

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Docker version 20.10.8, build 3967b7d

**Additional context**
It was working last week. No change to the guardian code.

**Comment by voycey** [comment]
To clarify - we can reproduce this by changing the clocks on the system, however our GKE cluster was running on UTC and we were seeing the same issue there. This was clearly related to daylight savings kicking in and gave us enough downtime to be noticeable here in Australia (where the effect is largest when EU / US clocks change).

**Comment by envisionblockchainpm** [comment]
This is the ticket for the Guardian Load Error we are getting as per @sergmetelin . This is an issue on the Hedera side, so today 11/18 we will be discussing with Hedera. The test for this issue was prepared already.

**Comment by envisionblockchainpm** [comment]
As per @Pyatakov We will wait for some time while working on getting the Guardian to load properly. ETA to close is Friday.

**Comment by envisionblockchainpm** [comment]
@envisionblockchainpm We are unable to reproduce this issue. Please check this issue and we will reopen the ticket if not fixed.

**Comment by envisionblockchainpm** [comment]
@engineforce I'm the Project Manager for this issue and was wondering if you could check to see if this was fixed. Our Dev Team has mentioned this is now fixed. - Thanks in Advance!

**Comment by engineforce** [comment]
Will check today

**Comment by engineforce** [comment]
Hi @envisionblockchainpm,

Sorry I can still reproduce this today, by changing my clock to 1 hour before

```
guardian-service_1  | /usr/vc-modules/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23
guardian-service_1  |     super(props, `transaction ${props.transactionId.toString()} failed precheck with status ${props.status.toString()}`);
guardian-service_1  |     ^
guardian-service_1  |
guardian-service_1  | PrecheckStatusError: transaction 0.0.2966684@1638150893.879241968 failed precheck with status TRANSACTION_EXPIRED
guardian-service_1  |     at new PrecheckStatusError (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)
guardian-service_1  |     at TopicCreateTransaction._mapStatusError (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:944:12)
guardian-service_1  |     at TopicCreateTransaction.execute (/usr/vc-modules/node_modules/@hashgraph/sdk/lib/Executable.cjs:392:22)
guardian-service_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
guardian-service_1  |   status: Status { _code: 4 },
guardian-service_1  |   transactionId: TransactionId {
guardian-service_1  |     accountId: AccountId {
guardian-service_1  |       shard: Long { low: 0, high: 0, unsigned: false },
guardian-service_1  |       realm: Long { low: 0, high: 0, unsigned: false },
guardian-service_1  |       num: Long { low: 2966684, high: 0, unsigned: false },
guardian-service_1  |       _checksum: null
guardian-service_1  |     },
guardian-service_1  |     validStart: Timestamp {
guardian-service_1  |       seconds: Long { low: 1638150893, high: 0, unsigned: false },
guardian-service_1  |       nanos: Long { low: 879241968, high: 0, unsigned: false }
guardian-service_1  |     },
guardian-service_1  |     scheduled: false
guardian-service_1  |   }
guardian-service_1  | }
```

Following are the steps:

1. Make sure `guardian-service/config.json` only contains `OPERATOR_ID` and `OPERATOR_KEY`, no other properties, which force guardian service to generate other properties
2. `docker-compose down`
3. Change to clock to 1 hour before the current time (I am in Melbourne)
4. `docker-compose up --build`

**Comment by voycey** [comment]
Australia at the moment vs the US is a +16 hour difference to EST, a lot of libraries for some reason max out at 12 hours, this has been the cause of frustration to us in the past a lot as often when trying to calculate date deltas the maths doesn't work.

We are currently on Australian Eastern Daylight Time (GMT / UTC +11) in Melbourne

**Comment by voycey** [comment]
@envisionblockchainpm - any response on the above? We are in the process of implementing this and want to ensure next time the clocks change this doesnt fail as that will be right around the launch time with a big customer

**Comment by envisionblockchainpm** [comment]
@voycey and @engineforce Good Morning Gentleman. We are checking on this and I will get back to you.

**Comment by engineforce** [comment]
@envisionblockchainpm This is happening again since 4pm Melbourne Time (2022-01-16) without modifying my system time.

Following are the logs from your latest `main`

```
docker-compose logs -f --timestamps guardian-service

Attaching to engineforce-guardian_guardian-service_1
guardian-service_1  | 2022-01-16T00:31:49.962813000Z
guardian-service_1  | 2022-01-16T00:31:49.962859300Z > guardian-service@1.0.2 start
guardian-service_1  | 2022-01-16T00:31:49.962878700Z > node dist/index.js
guardian-service_1  | 2022-01-16T00:31:49.962898000Z
guardian-service_1  | 2022-01-16T00:31:52.593596300Z (node:19) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
guardian-service_1  | 2022-01-16T00:31:52.593648400Z (Use `node --trace-warnings ...` to show where the warning was created)
guardian-service_1  | 2022-01-16T00:32:52.704235500Z node:internal/process/promises:246
guardian-service_1  | 2022-01-16T00:32:52.704300000Z           triggerUncaughtException(err, true /* fromPromise */);
guardian-service_1  | 2022-01-16T00:32:52.704320900Z           ^
guardian-service_1  | 2022-01-16T00:32:52.704338200Z
guardian-service_1  | 2022-01-16T00:32:52.704355000Z [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Failed to create Address Book:
guardian-service_1  | 2022-01-16T00:32:52.704395900Z Transaction timeout exceeded".] {
guardian-service_1  | 2022-01-16T00:32:52.704416200Z   code: 'ERR_UNHANDLED_REJECTION'
guardian-service_1  | 2022-01-16T00:32:52.704433500Z }
engineforce-guardian_guardian-service_1 exited with code 1
```

**Comment by envisionblockchainpm** [comment]
@engineforce Glad you brought this up as we are working on this issue in this sprint now. I will update you this week. Cheers
