### ISSUE TITLE
Bug: Can not delete schema

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#901]
### Problem description
- This caused by the Nats implementation wrong for DELETE_SCHEMA action
- The reason is the payload was encrypted as stringEncode but decoded using jsonDecode. The simple fix for this is in update request/response function to send json object

### Step to reproduce
1. create empty schema
2. delete schema -> error
```/usr/common/node_modules/nats/lib/nats-base-client/error.js:98

        return new NatsError(m, code, chainedError);

               ^


NatsError: Bad JSON

    at Function.errorForCode (/usr/common/node_modules/nats/lib/nats-base-client/error.js:98:16)

    at Object.decode (/usr/common/node_modules/nats/lib/nats-base-client/codec.js:50:41)

    at MessageBrokerChannel.<anonymous> (/usr/common/dist/mq/index.js:56:41)

    at Generator.next (<anonymous>)

    at fulfilled (/usr/common/dist/mq/index.js:5:58)

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

  code: 'BAD_JSON',

  chainedError: SyntaxError: Unexpected token a in JSON at position 3

      at JSON.parse (<anonymous>)

      at Object.decode (/usr/common/node_modules/nats/lib/nats-base-client/codec.js:47:29)

      at MessageBrokerChannel.<anonymous> (/usr/common/dist/mq/index.js:56:41)

      at Generator.next (<anonymous>)

      at fulfilled (/usr/common/dist/mq/index.js:5:58)

      at processTicksAndRejections (node:internal/process/task_queues:96:5)

}
```

### Expected behavior
It should able to delete schema

**Comment by samuraitruong** [comment]
@anvabr  can you assign this to me please. will have PR soon
